name: ai2es-sharpness-v2
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.24.4
  - scipy=1.10.1
  - matplotlib=3.7.3
  - xarray=2023.1.0
  - netcdf4=1.6.5
  - dask=2023.5.0
  - pandas=1.5.3
  - scikit-learn=1.3.2
  - pyyaml=6.0.1
  - pytest=7.4.4
  - distributed=2023.5.0
  - pip=23.3.2
  - pyproj=3.5.0
  - jupyter
  - jupyterlab=4.0.10
  - cartopy=0.21.1
  - tqdm=4.66.1
  - sphinx=7.1.2
  - numba=0.58.1
  - cython=3.0.7
  - pip:
    - opencv-python==4.9.0.80
    - scikit-image==0.21.0
    - .
